const LABELS_EN = {
    app_title: 'Fault and Repair Injection App',
    form_ip: 'IP',
    form_ssh_username: 'SSH Username',
    form_ssh_password: 'SSH Password',
    form_autodetect_network_interface: 'Autodetect network interface',
    form_network_interface_id: 'Network interface identifier',
    form_fault_types: 'Fault Types',
    form_hardware: 'Hardware',
    form_os: 'Operating System (S.O.)',
    form_ttf_hw: 'TTF (Hardware)',
    form_ttr_hw: 'TTR (Hardware)',
    form_ttf_os: 'TTF (S.O.)',
    form_ttr_os: 'TTR (S.O.)',
    form_vm_name: 'VM Name (VBoxManage)',
    form_experiment_attempts: 'Experiment Attempts',
    form_attempts: 'attempts',
    form_download_log: 'Download Log',
    form_clear_monitor: 'Clear',
    form_copy_monitor: 'Copy',
    form_inject: 'Inject',
    form_yes: 'Yes',
    form_no: 'No',
    form_error_select_fault: 'Select at least one fault type.',
    status_up: 'up',
    status_down: 'down',
}

const LABELS_PT_BR = {
    app_title: 'Aplicativo de injeção de falhas e reparos',
    form_ip: 'IP',
    form_ssh_username: 'Usuário SSH',
    form_ssh_password: 'Senha SSH',
    form_autodetect_network_interface: 'Auto detectar interface de rede',
    form_network_interface_id: 'Identificador da interface de rede',
    form_fault_types: 'Tipos de Falha',
    form_hardware: 'Hardware',
    form_os: 'Sistema Operacional (S.O.)',
    form_ttf_hw: 'TDF (Hardware)',
    form_ttr_hw: 'TDR (Hardware)',
    form_ttf_os: 'TDF (S.O.)',
    form_ttr_os: 'TDR (S.O.)',
    form_vm_name: 'Nome da VM (VBoxManage)',
    form_experiment_attempts: 'Tentativas do Experimento',
    form_attempts: 'tentativas',
    form_download_log: 'Baixar registro de eventos',
    form_clear_monitor: 'Limpar',
    form_copy_monitor: 'Copiar',
    form_inject: 'Injetar',
    form_yes: 'Sim',
    form_no: 'Não',
    form_error_select_fault: 'Selecione pelo menos um tipo de falha.',
    status_up: 'up',
    status_down: 'down',
}

export const LABELS = process.env.NEXT_PUBLIC_APP_LANGUAGE == 'pt-br' ? LABELS_PT_BR : LABELS_EN
